name: carros
description: Carros.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  connectivity: ^0.4.8+2
  http: ^0.12.0+4
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6+3
  sqflite: ^1.3.0
  image_picker: ^0.6.4
  provider: ^4.0.4
  share: ^0.6.3+6
  url_launcher: ^5.4.2
  video_player: ^0.10.8+1
  google_maps_flutter: ^0.5.25+3
  flutter_auth_buttons: ^0.8.0
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.1
  cloud_firestore: ^0.13.4+2
  firebase_messaging: ^6.0.13
  firebase_remote_config: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sql/
    - assets/images/
